[workspace]
members = ["cli", "lib"]

[workspace.package]
version = "0.1.0"
authors = ["Takahiro Ebato <takahiro.ebato@gmail.com>"]
homepage = "https://github.com/takaebato/sql-insight"
repository = "https://github.com/takaebato/sql-insight"
license = "Apache-2.0"
edition = "2021"
