[package]
name = "sql-insight"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.56"
sqlparser = { version = "0.41.0", features = ["visitor"] }
tap = { version = "1.0.1" }
